baseURL = 'https://answndud.github.io/MoonJuYoungBlog/'
languageCode = 'ko-kr'
title = 'My Blog'
theme = 'PaperMod'

# ë¹Œë“œ ì˜µì…˜
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# í˜ì´ì§€ë„¤ì´ì…˜
[pagination]
pagerSize = 10

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
author = "Your Name"
description = "ê°œì¸ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤."
keywords = ["Blog", "Portfolio", "Personal"]
DateFormat = "2006ë…„ 1ì›” 2ì¼"

defaultTheme = "auto"  # auto, light, dark
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.homeInfoParams]
Title = "ì•ˆë…•í•˜ì„¸ìš” ğŸ‘‹"
Content = "ê°œì¸ ë¸”ë¡œê·¸ì— ì˜¤ì‹  ê²ƒì„ í™˜ì˜í•©ë‹ˆë‹¤."

# Giscus ëŒ“ê¸€ ì„¤ì •
[params.giscus]
repo = "answndud/MoonJuYoungBlog"
repoId = "R_kgDORC6yYQ"
category = "General"
categoryId = "DIC_kwDORC6yYc4Cmq_5"
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "ko"
loading = "lazy"

[[params.socialIcons]]
name = "github"
url = "https://github.com/answndud"

[[params.socialIcons]]
name = "email"
url = "mailto:your@email.com"

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

[params.editPost]
URL = "https://github.com/answndud/MoonJuYoungBlog/tree/main/content"
Text = "ì œì•ˆí•˜ê¸°"
appendFilePath = true

# ê²€ìƒ‰ ê¸°ëŠ¥
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

# ë©”ë‰´
[[menu.main]]
identifier = "posts"
name = "ì „ì²´ ê¸€"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "ì¹´í…Œê³ ë¦¬"
url = "/categories/"
weight = 15

[[menu.main]]
identifier = "cat-finance"
name = "Finance"
url = "/categories/finance/"
weight = 20

[[menu.main]]
identifier = "cat-cs"
name = "CS"
url = "/categories/cs/"
weight = 21

[[menu.main]]
identifier = "cat-security"
name = "Security"
url = "/categories/security/"
weight = 22


[[menu.main]]
identifier = "archives"
name = "ì•„ì¹´ì´ë¸Œ"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "íƒœê·¸"
url = "/tags/"
weight = 40

[[menu.main]]
identifier = "search"
name = "ê²€ìƒ‰"
url = "/search/"
weight = 50

# ê²€ìƒ‰ í˜ì´ì§€ ì¶œë ¥ í˜•ì‹
[outputs]
home = ["HTML", "RSS", "JSON"]
